### PR TITLE
Requests will now contain an absolute request uri

### LINKED ISSUE #30: Log full URI on request
Currently protocol and host are omitted when logging the request `URI`. It would be cool if we could have the full `URI` there.

	{
	  "correlation": "40e13d1e-3b57-4a94-a954-90df38bbc12c",
	  "remote": "172.17.0.1",
	  "method": "GET",
	  "uri": "/oauth2/tokeninfo?access_token=XXX",
	  "headers": {
	    "Accept": [
	      "application/json, application/*+json"
	    ],
	    "User-Agent": [
	      "Apache-HttpClient/4.5.1 (Java/1.8.0_66-internal)"
	    ],
	    "Connection": [
	      "Keep-Alive"
	    ],
	    "Host": [
	      "rhino.example.org"
	    ],
	    "Accept-Encoding": [
	      "gzip,deflate"
	    ]
	  }
	}

### PR DESCRIPTION
**Pull request by whiskeysierra**
This fixes #30

### CODE REVIEW

**Comment by lukasniemeier** [comment]
:+1:

**Comment by whiskeysierra** [comment]
For the servlet filter this is easy, as it provides [`HttpServletRequest.getRequestURL`](http://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#getRequestURL--).
The HTTP Client on the other hand unfortunately wraps the request inside an [`HttpRequestWrapper`](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/methods/HttpRequestWrapper.html) which rewrites the URI to `/` (or whatever the path was).

**Comment by whiskeysierra** [comment]
I modified it again and even though it's pretty ugly it should work now.

**Comment by whiskeysierra** [comment]
@lukasniemeier Should we have both versions available, fully qualified vs. path?

**Comment by whiskeysierra** [comment]
> @lukasniemeier Should we have both versions available, fully qualified vs. path?

I'll merge this now. If we decide to do that I'm going to open another issue/pull-request.

**Pull request merged**
