### PR TITLE
Dedicated spring-webflux module

### PR DESCRIPTION
**Pull request by sokomishalov**
## Description
A separate webflux connector-independent module

## Motivation and Context
This module could be useful for non-netty users and be a starting point for issues like #1098.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
@sokomishalov I'd be very happy to see this making it into Logbook. There seems to be a dependency clash right now. Can you take a look?

**Comment by sokomishalov** [comment]
@whiskeysierra sure, I've fixed it and coverage issues.

**Comment by whiskeysierra** [comment]
👍

**Comment by whiskeysierra** [comment]
@sokomishalov Thank you for your contribution! 🎉

**Comment by PascalSchumacher** [comment]
@sokomishalov Thank you very much for implementing this! 👍 😃 

I noticed that log messages produced by `LogbookExchangeFilterFunction` seem to be missing headers compared to `LogbookClientHandler`:

LogbookClientHandler:
```
Outgoing Request: c1b96b4bc972c9cd
Remote: REMOTE_HOST:REMOTE_PORT
PATCH REMOTE_URL HTTP/1.1
accept: */*
Authorization: XXX
content-length: 359
Content-Type: application/json
host: REMOTE_HOST:REMOTE_PORT
user-agent: ReactorNetty/1.0.13
CustomHeader: CustomHeaderValue
```

LogbookExchangeFilterFunction:
```
Outgoing Request: 8f9f882da93f2ae4
Remote: localhost
PATCH REMOTE_URL HTTP/1.1
CustomHeader: CustomHeaderValue
```

I guess it is not possible to log the missing headers because they are not available to `ClientRequest`?

**Comment by sokomishalov** [comment]
@PascalSchumacher I've investigated your issue a bit. Most of these headers apply on the connector side (netty) and are unavailable from spring-web public API. The only way is to get a native request by performing a classpath check for native request. But I guess the right way to fix this is to raise issue/provide pr to spring-web to provide correct implementation on the spring-side.

**Pull request merged**
