### PR TITLE
Fix PathNotFoundException when body is unwrapped Array

### PR DESCRIPTION
**Pull request by ismail2ov**
Fix PathNotFoundException when body is unwrapped Array

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
> Fix PathNotFoundException when body is unwrapped Array

What do you mean with unwrapped array? Can you give a sample request that fails right now?

**Comment by ismail2ov** [comment]
Yes, I have added the JSON in the test resources [cars-unwrapped-array.json](https://github.com/zalando/logbook/blob/5c86c0f6a6020391967117c252c406c0647c1f2e/logbook-json/src/test/resources/cars-unwrapped-array.json) and also the test

**Comment by whiskeysierra** [comment]
So if I'm understanding this correctly, you just use an array as the top level JSON element in your request body, right?

But this should be supported by JsonPath if you e.g. use this filter expression `$[*].name`, shouldn't it?

**Comment by whiskeysierra** [comment]
Just tested it here and it works: https://jsonpath.com/

**Comment by ismail2ov** [comment]
You are absolutely right, and this works. 
The corner case is when we have a filter that we try to apply and it has the following format:
`jsonPath("$.*.name")` and the body is unwrapped array, we receive NPE in this lines:
`return operation.filter(original).jsonString();`

**Comment by whiskeysierra** [comment]
If you want to replace `name` properties, regardless of the depth or whether they are nested within arrays or not, you should use `$..name`.

**Comment by whiskeysierra** [comment]
I'd like to see your original code that failed, because the test is now tailored towards the changed code, not the original one.

**Comment by ismail2ov** [comment]
If you run the test replacesValuesDynamicallyWhenBodyIsUnwrappedArray() from class JsonPathBodyFiltersTest without the changes in JsonPathBodyFilters, this will fail  with exception

**Comment by whiskeysierra** [comment]
I did, but the only thing failing with an exception is the assertion:

```
/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -ea -Didea.test.cyclic.buffer.size=1048576 -javaagent:/Users/willi.schoenborn/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5080.55/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=53982:/Users/willi.schoenborn/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5080.55/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Users/willi.schoenborn/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5080.55/IntelliJ IDEA.app/Contents/lib/idea_rt.jar:/Users/willi.schoenborn/.m2/repository/org/junit/platform/junit-platform-launcher/1.8.1/junit-platform-launcher-1.8.1.jar:/Users/willi.schoenborn/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5080.55/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit5-rt.jar:/Users/willi.schoenborn/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5080.55/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit-rt.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/tools.jar:/Users/willi.schoenborn/Projects/oss/logbook/logbook-json/target/test-classes:/Users/willi.schoenborn/Projects/oss/logbook/logbook-json/target/classes:/Users/willi.schoenborn/Projects/oss/logbook/logbook-api/target/classes:/Users/willi.schoenborn/.m2/repository/org/organicdesign/Paguro/3.1.4/Paguro-3.1.4.jar:/Users/willi.schoenborn/Projects/oss/logbook/logbook-common/target/classes:/Users/willi.schoenborn/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.5/jackson-databind-2.12.5.jar:/Users/willi.schoenborn/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.12.5/jackson-core-2.12.5.jar:/Users/willi.schoenborn/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.12.5/jackson-annotations-2.12.5.jar:/Users/willi.schoenborn/.m2/repository/com/jayway/jsonpath/json-path/2.6.0/json-path-2.6.0.jar:/Users/willi.schoenborn/Projects/oss/logbook/logbook-test/target/classes:/Users/willi.schoenborn/.m2/repository/org/slf4j/slf4j-nop/1.7.32/slf4j-nop-1.7.32.jar:/Users/willi.schoenborn/.m2/repository/com/jayway/jsonpath/json-path-assert/2.6.0/json-path-assert-2.6.0.jar:/Users/willi.schoenborn/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar:/Users/willi.schoenborn/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/willi.schoenborn/.m2/repository/com/google/gag/gag/1.0.1/gag-1.0.1.jar:/Users/willi.schoenborn/.m2/repository/org/projectlombok/lombok/1.18.20/lombok-1.18.20.jar:/Users/willi.schoenborn/.m2/repository/org/zalando/faux-pas/0.9.0/faux-pas-0.9.0.jar:/Users/willi.schoenborn/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/Users/willi.schoenborn/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.32/jcl-over-slf4j-1.7.32.jar:/Users/willi.schoenborn/.m2/repository/com/google/guava/guava/30.1.1-jre/guava-30.1.1-jre.jar:/Users/willi.schoenborn/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/Users/willi.schoenborn/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/Users/willi.schoenborn/.m2/repository/org/checkerframework/checker-qual/3.8.0/checker-qual-3.8.0.jar:/Users/willi.schoenborn/.m2/repository/com/google/errorprone/error_prone_annotations/2.5.1/error_prone_annotations-2.5.1.jar:/Users/willi.schoenborn/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:/Users/willi.schoenborn/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.8.1/junit-jupiter-api-5.8.1.jar:/Users/willi.schoenborn/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/Users/willi.schoenborn/.m2/repository/org/junit/platform/junit-platform-commons/1.8.1/junit-platform-commons-1.8.1.jar:/Users/willi.schoenborn/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.8.1/junit-jupiter-engine-5.8.1.jar:/Users/willi.schoenborn/.m2/repository/org/junit/platform/junit-platform-engine/1.8.1/junit-platform-engine-1.8.1.jar:/Users/willi.schoenborn/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.8.1/junit-jupiter-params-5.8.1.jar:/Users/willi.schoenborn/.m2/repository/org/assertj/assertj-core/3.21.0/assertj-core-3.21.0.jar:/Users/willi.schoenborn/.m2/repository/org/mockito/mockito-core/3.12.4/mockito-core-3.12.4.jar:/Users/willi.schoenborn/.m2/repository/net/bytebuddy/byte-buddy/1.11.13/byte-buddy-1.11.13.jar:/Users/willi.schoenborn/.m2/repository/net/bytebuddy/byte-buddy-agent/1.11.13/byte-buddy-agent-1.11.13.jar:/Users/willi.schoenborn/.m2/repository/org/objenesis/objenesis/3.2/objenesis-3.2.jar:/Users/willi.schoenborn/.m2/repository/org/mockito/mockito-junit-jupiter/3.12.4/mockito-junit-jupiter-3.12.4.jar:/Users/willi.schoenborn/.m2/repository/org/hamcrest/hamcrest/2.2/hamcrest-2.2.jar com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit5 org.zalando.logbook.json.JsonPathBodyFiltersTest

java.lang.AssertionError: Error reading JSON path [content[0].name]

	at com.jayway.jsonassert.impl.JsonAsserterImpl.assertThat(JsonAsserterImpl.java:36)
	at com.jayway.jsonassert.impl.JsonAsserterImpl.assertEquals(JsonAsserterImpl.java:64)
	at org.zalando.logbook.json.JsonPathBodyFiltersTest.replacesValuesDynamicallyWhenBodyIsUnwrappedArray(JsonPathBodyFiltersTest.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: com.jayway.jsonpath.PathNotFoundException: Expected to find an object with property ['content'] in path $ but found 'java.util.ArrayList'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JacksonJsonProvider'.
	at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:71)
	at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:99)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:107)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:185)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:89)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:78)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:529)
	at com.jayway.jsonassert.impl.JsonAsserterImpl.assertThat(JsonAsserterImpl.java:34)
	... 69 more
```

**Comment by whiskeysierra** [comment]
When I change the test to:

```java
@Test
void replacesValuesDynamicallyWhenBodyIsUnwrappedArray() throws IOException {
    String cars = Resources.toString(getResource("cars-unwrapped-array.json"), UTF_8);

    final BodyFilter unit = jsonPath("$.content[*].name").replace(String::toUpperCase);

    with(unit.filter(type, cars))
            .assertEquals("[0].name", "FORD")
            .assertEquals("[1].name", "BMW")
            .assertEquals("[2].name", "FIAT");
}
```

then the test fails with:

```
java.lang.AssertionError: JSON path [[0].name] doesn't match.
Expected:
"FORD"
Actual:
Ford
```

**Comment by whiskeysierra** [comment]
If I then change the filter to `"$..name"` the test passes.

**Comment by whiskeysierra** [comment]
`"$.*.name"` works as well.

**Comment by ismail2ov** [comment]
Change the test as like this:
```
@Test
void replacesValuesDynamicallyWhenBodyIsUnwrappedArray() throws IOException {
    String cars = Resources.toString(getResource("cars-unwrapped-array.json"), UTF_8);

    final BodyFilter unit = jsonPath("$.content[*].name").replace(String::toUpperCase);

    unit.filter(type, cars);
}
```

**Comment by whiskeysierra** [comment]
Just tried that. I changed the test as you specified and reverted the changes in `JsonPathBodyFilters`. Tests are still green.

Can you revert your fix, just leave in a test that fails on the main branch today and update your PR?
CI should show the issue then.

**Comment by ismail2ov** [comment]
Done

**Comment by ismail2ov** [comment]
> If I then change the filter to `"$..name"` the test passes.

I agree with you, this works, but we have many micro services that interact with many systems and we cannot verify if the deep scan operator is used everywhere like this `"$..name"`, when the optimal way to use is `"$.name" `.
IMHO, no matter how replacement patterns are used, the service should work without launching. If the pattern is not correct, no or apply.

**Comment by whiskeysierra** [comment]
Thanks for the update of the PR to see the failure.

I checked it out locally and there is an option for JsonPath that when enabled makes all tests pass:

```
.options(Option.ALWAYS_RETURN_LIST)
```

**Comment by ismail2ov** [comment]
> I checked it out locally and there is an option for JsonPath that when enabled makes all tests pass:
> 
> ```
> .options(Option.ALWAYS_RETURN_LIST)
> ```
I have checked it and it works. 
Can you apply it? 
```
Index: logbook-json/src/main/java/org/zalando/logbook/json/JsonPathBodyFilters.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/logbook-json/src/main/java/org/zalando/logbook/json/JsonPathBodyFilters.java b/logbook-json/src/main/java/org/zalando/logbook/json/JsonPathBodyFilters.java
--- a/logbook-json/src/main/java/org/zalando/logbook/json/JsonPathBodyFilters.java	(revision 0b62d158342b7dcc07e0fb9a1db6de5e61e069c0)
+++ b/logbook-json/src/main/java/org/zalando/logbook/json/JsonPathBodyFilters.java	(date 1632472057685)
@@ -87,6 +87,7 @@
                         .jsonProvider(new JacksonJsonNodeJsonProvider())
                         .mappingProvider(new JacksonMappingProvider())
                         .options(Option.SUPPRESS_EXCEPTIONS)
+                        .options(Option.ALWAYS_RETURN_LIST)
                         .build());
 
         private final Operation operation;
```

**Comment by whiskeysierra** [comment]
If you apply it to this PR I can just merge it.

**Comment by ismail2ov** [comment]
@whiskeysierra is already applied

**Comment by whiskeysierra** [comment]
👍

**Comment by ismail2ov** [comment]
@whiskeysierra you are right.
I created this PR https://github.com/zalando/logbook/pull/1179

**Pull request merged**
