### PR TITLE
Fix logging of duplicate header names

### LINKED ISSUE #42: Duplicate key exception when logging response headers in spring boot application
java.lang.IllegalStateException: Duplicate key no-cache, no-store, max-age=0, must-revalidate
	at java.util.stream.Collectors.lambda$throwingMerger$156(Collectors.java:133) ~[?:1.8.0_65]
	at java.util.HashMap.merge(HashMap.java:1245) ~[?:1.8.0_65]
	at java.util.stream.Collectors.lambda$toMap$214(Collectors.java:1320) ~[?:1.8.0_65]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_65]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_65]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_65]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_65]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_65]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_65]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_65]
	at org.zalando.logbook.httpclient.Response.getHeaders(Response.java:62) ~[logbook-httpclient-0.11.0.jar:?]
	at org.zalando.logbook.ObfuscatedHttpResponse.getHeaders(ObfuscatedHttpResponse.java:49) ~[logbook-core-0.11.0.jar:?]
	at org.zalando.logbook.JsonHttpLogFormatter.format(JsonHttpLogFormatter.java:87) ~[logbook-core-0.11.0.jar:?]
	at org.zalando.logbook.DefaultLogbook.lambda$write$0(DefaultLogbook.java:55) ~[logbook-core-0.11.0.jar:?]
	at org.zalando.logbook.httpclient.LogbookHttpResponseInterceptor.process(LogbookHttpResponseInterceptor.java:39) ~[logbook-httpclient-0.11.0.jar:?]
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:141) ~[httpcore-4.4.3.jar:4.4.3]

### PR DESCRIPTION
**Pull request by jhorstmann**
Fixes #42

### CODE REVIEW

**Comment by whiskeysierra** [comment]
:+1:

**Comment by lukasniemeier** [comment]
Same in https://github.com/zalando/logbook/blob/master/logbook-httpclient/src/main/java/org/zalando/logbook/httpclient/Request.java ?

**Comment by jhorstmann** [comment]
Yes, I'll fix that too, but have to add some coverage first.

**Comment by lukasniemeier** [comment]
Very good

**Pull request merged**
