### PR TITLE
org.springframework.http.client.ClientHttpResponse interface change backwards compatibility

### PR DESCRIPTION
**Pull request by dipsk2**
## Description
Spring 6.x (boot 3.x) changed the interface org.springframework.http.client.ClientHttpResponse. The return type of getStatusCode() is changed. If we're on spring 5.x (or boot 2.x), there is a condition in which we get a NoSuchMethodError when using this method in our custom Sink.

This PR is to make the relevant method backwards compatible by catching this exception and trying the old way in case of failure.

## Motivation and Context
It fixes a bug with backwards compatibility with spring 5.x

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by dipsk2** [comment]
This is a blocker for us for the upgrade. Can someone please review this?

**Comment by kasmarian** [comment]
Hi @dipsk2, thank you for the contribution. Could you please merge in the latest main branch?

**Comment by dipsk2** [comment]
@kasmarian done

**Comment by kasmarian** [comment]
:+1:

**Pull request merged**
