### PR TITLE
End of support Spring Boot 1 and Spring Famework 4 

### PR DESCRIPTION
**Pull request by kasmarian**
## Description
As spring-boot 1.5 has reached it's commercial support on [2020-11-06](https://spring.io/projects/spring-boot#support), with these changes I propose to stop supporting it in Logbook as well.

## Motivation and Context
Support of older versions of Spring Framework and Spring Boot is becoming more problematic, it's a source of vulnerabilities, that can't be addressed, and number of potential users should be low at this point. 

Clients will still be able to use Logbook versions that support older versions of the Spring Framework.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by kasmarian** [comment]
@whiskeysierra I've opened this PR to kick off the discussion if we really need to support old spring versions. 
After a short interaction with the library, I learned that spring4 related builds are more fragile ([latest example](https://github.com/zalando/logbook/pull/1298)), but I fail to understand if the time spent on fixing them is well spent, considering that end of support happened long time ago for Spring Boot 1. 
I'd appreciate your opinion here.

P.s. how do I get rid of `build (spring4)` status?

**Comment by whiskeysierra** [comment]
> I'd appreciate your opinion here.

Yeah, support for Spring 4 and Spring Boot 1 should be discontinued for Logbook, imo.

> P.s. how do I get rid of `build (spring4)` status?

You need to modify the github action and then the build requirement (in the settings of this repo).

**Comment by msdousti** [comment]
It will be great if we merge this sooner.
Regarding @whiskeysierra's comment below:

> and then the build requirement (in the settings of this repo).

I guess only authorized people can access `settings`:
image

**Comment by kasmarian** [comment]
@lukasniemeier-zalando can you please assist with removing the `spring4` step from the build requirement?

**Comment by kasmarian** [comment]
:+1:

**Comment by otrosien** [comment]
👍

**Pull request merged**
