### PR TITLE
fix: README PathFilter based on property name typo

### PR DESCRIPTION
**Pull request by brnhrdt**
Only a small typo fix for PathFilter description in the LogbookAutoconfig section

### CODE REVIEW

**Comment by fatroom** [comment]
Thanks for catching. Seems that PathFilter was copied from headers filters. Looking on source code here would you mind to fix this reference as well? https://github.com/zalando/logbook/blob/51b8abc3ce465a6959aa122895ca22624d0c0532/logbook-api/src/main/java/org/zalando/logbook/PathFilter.java#L18 (should be path instead of headers)

**Comment by brnhrdt** [comment]
It's fixed. Thanks guys for the great work making logbook! I'm happy I could contribute a tiny bit :)

**Comment by fatroom** [comment]
👍

**Comment by whiskeysierra** [comment]
Thanks for your contribution! 📣

**Pull request merged**
