### PR TITLE
Moved flushing of async response to correct branch

### LINKED ISSUE #143: There is no Content-Type header in response with async requests
I have a spring controller that is defined like this:

@GetMapping(path = "somePath" produces = MediaType.APPLICATION_JSON_VALUE)
public ListenableFuture<SomeClass> retrieveSomething() {
    ...
}

Without logbook it returns the content type header, with logbook autoconfiguration the header is missing in response.

I haven't done any debuging on this issue. So i can not provide more details. Sorry.

### PR DESCRIPTION
**Pull request by whiskeysierra**
Fixes #143

@iribaar @wyzssw @cybuch

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
Do you test it with external setup?

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by whiskeysierra** [comment]
> Do you test it with external setup?

Yes. It's not testable with Spring's MockMvc.

**Comment by cybuch** [comment]
:+1:

**Pull request merged**
