### PR TITLE
GH-198 Uses pseudo-random generator to create correlation ids

### LINKED ISSUE #198: It is slow when generate correlation Id
This is a picture profiled  on my production server.
It stuck at UUID.randomUUID(),
```
java.security.SecureRandom#nextBytes
  @Override
    synchronized public void nextBytes(byte[] bytes) {
        secureRandomSpi.engineNextBytes(bytes);
    }

```

4c694acf-bc0c-40e8-a35e-23061077b2c5

UUID performance is very slow，could logbook use random instead of uuid?
```https://stackoverflow.com/questions/14532976/performance-of-random-uuid-generation-with-java-7-or-java-6```

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
Fixes #198

### CODE REVIEW

**Comment by whiskeysierra** [comment]
:+1:

**Comment by whiskeysierra** [comment]
1.5.3, it's already in central.

**Comment by Leyisba15** [comment]
Bonjour je recherche un zalando generator

**Comment by whiskeysierra** [comment]
Are you looking for this?

https://github.com/zalando/logbook/blob/02ad199aab98cd787037b22cdcaa38306e7945f3/logbook-core/src/main/java/org/zalando/logbook/DefaultCorrelationId.java#L10-L20

That's the current default implementation which generates correlation ids.

**Comment by Leyisba15** [comment]
No give to my please

Le mer. 16 déc. 2020 à 03:47, Willi Schönborn <notifications@github.com> a
écrit :

**Comment by whiskeysierra** [comment]
Sorry, no clue what you want.

**Comment by Leyisba15** [comment]
What do you mean?

Le mer. 16 déc. 2020 à 06:42, Willi Schönborn <notifications@github.com> a
écrit :

**Comment by whiskeysierra** [comment]
I don't understand what you want or need.

**Comment by Leyisba15** [comment]
I am looking for a zalando generator

[image: Icône de validation par la communauté]
------------------------------


Le mer. 16 déc. 2020 à 06:56, Willi Schönborn <notifications@github.com> a
écrit :

**Comment by whiskeysierra** [comment]
What does that mean? What is "Zalando Generator"?

**Comment by Leyisba15** [comment]
I'm looking for credit cards


Le mer. 16 déc. 2020 à 07:25, Willi Schönborn <notifications@github.com> a
écrit :

> What does that mean? What is "Zalando Generator"?
>

**Pull request merged**
