### PR TITLE
Fix dependency scopes

### LINKED ISSUE #1711: Logbook 3.7.1 pulls in a whole bunch of test dependencies to the production classpath
Note: This issue is related to https://github.com/zalando/logbook/issues/1705.

When upgrading Logbook from `3.6.0` to `3.7.1`, Gradle adds a whole bunch of test dependencies to the production or runtime classpath.

## Steps to reproduce

1. Create a new Gradle / Spring Boot project (use [start.spring.io](https://start.spring.io/) or IntelliJ’s native integration)
2. Add Logbook **3.6.0** as dependency: `org.zalando:logbook-spring-boot-starter:3.6.0`
3. Enable [Gradle Dependency Locking](https://docs.gradle.org/current/userguide/dependency_locking.html) by adding the following lines to your `build.gradle`/`build.gradle.kts`:
```
dependencyLocking {
    lockAllConfigurations()
}
```
4. Create the lockfile using `./gradlew dependencies --write-locks`
5. Update Logbook from `3.6.0` and `3.7.1`, and update the lockfile using `./gradlew dependencies --write-locks`

## Expected behavior

The new lockfile version shows that the logbook version changes from `3.6.0` to `3.7.1` and probably a few new dependencies are introduced

## Actual behavior

A whole bunch of test dependencies such as `assertj-core`, `hamcrest`, `junit`, `opentest4j` etc. are pulled into the production/runtime classpath.
That’s the full diff on my Gradle lockfile:

```diff
--- a/gradle.lockfile
+++ b/gradle.lockfile
@@ -14,30 +14,32 @@ io.micrometer:micrometer-commons:1.12.0=compileClasspath,productionRuntimeClassp
 io.micrometer:micrometer-observation:1.12.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
 jakarta.activation:jakarta.activation-api:2.1.2=testCompileClasspath,testRuntimeClasspath
 jakarta.annotation:jakarta.annotation-api:2.1.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+jakarta.servlet:jakarta.servlet-api:6.0.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
 jakarta.xml.bind:jakarta.xml.bind-api:4.0.1=testCompileClasspath,testRuntimeClasspath
-net.bytebuddy:byte-buddy-agent:1.14.10=testCompileClasspath,testRuntimeClasspath
-net.bytebuddy:byte-buddy:1.14.10=testCompileClasspath,testRuntimeClasspath
+net.bytebuddy:byte-buddy-agent:1.14.10=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+net.bytebuddy:byte-buddy:1.14.10=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
 net.minidev:accessors-smart:2.5.0=testCompileClasspath,testRuntimeClasspath
 net.minidev:json-smart:2.5.0=testCompileClasspath,testRuntimeClasspath
 org.apache.logging.log4j:log4j-api:2.21.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
 org.apache.logging.log4j:log4j-to-slf4j:2.21.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
 org.apiguardian:apiguardian-api:1.1.2=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
-org.assertj:assertj-core:3.24.2=testCompileClasspath,testRuntimeClasspath
+org.assertj:assertj-core:3.24.2=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
 org.awaitility:awaitility:4.2.0=testCompileClasspath,testRuntimeClasspath
-org.hamcrest:hamcrest:2.2=testCompileClasspath,testRuntimeClasspath
-org.junit.jupiter:junit-jupiter-api:5.10.1=testCompileClasspath,testRuntimeClasspath
-org.junit.jupiter:junit-jupiter-engine:5.10.1=testRuntimeClasspath
-org.junit.jupiter:junit-jupiter-params:5.10.1=testCompileClasspath,testRuntimeClasspath
+org.hamcrest:hamcrest:2.2=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.junit.jupiter:junit-jupiter-api:5.10.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.junit.jupiter:junit-jupiter-engine:5.10.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.junit.jupiter:junit-jupiter-params:5.10.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
 org.junit.jupiter:junit-jupiter:5.10.1=testCompileClasspath,testRuntimeClasspath
-org.junit.platform:junit-platform-commons:1.10.1=testCompileClasspath,testRuntimeClasspath
-org.junit.platform:junit-platform-engine:1.10.1=testRuntimeClasspath
-org.junit:junit-bom:5.10.1=testCompileClasspath,testRuntimeClasspath
-org.mockito:mockito-core:5.7.0=testCompileClasspath,testRuntimeClasspath
-org.mockito:mockito-junit-jupiter:5.7.0=testCompileClasspath,testRuntimeClasspath
-org.objenesis:objenesis:3.3=testRuntimeClasspath
-org.opentest4j:opentest4j:1.3.0=testCompileClasspath,testRuntimeClasspath
+org.junit.platform:junit-platform-commons:1.10.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.junit.platform:junit-platform-engine:1.10.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.junit:junit-bom:5.10.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.mockito:mockito-core:5.7.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.mockito:mockito-junit-jupiter:5.7.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.objenesis:objenesis:3.3=productionRuntimeClasspath,runtimeClasspath,testRuntimeClasspath
+org.opentest4j:opentest4j:1.3.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
 org.ow2.asm:asm:9.3=testCompileClasspath,testRuntimeClasspath
 org.skyscreamer:jsonassert:1.5.1=testCompileClasspath,testRuntimeClasspath
+org.slf4j:jcl-over-slf4j:2.0.9=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
 org.slf4j:jul-to-slf4j:2.0.9=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
 org.slf4j:slf4j-api:2.0.9=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
 org.springframework.boot:spring-boot-autoconfigure:3.2.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
@@ -57,12 +59,12 @@ org.springframework:spring-test:6.1.1=testCompileClasspath,testRuntimeClasspath
 org.xmlunit:xmlunit-core:2.9.1=testCompileClasspath,testRuntimeClasspath
 org.yaml:snakeyaml:2.2=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
 org.zalando:faux-pas:0.9.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
-org.zalando:logbook-api:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
-org.zalando:logbook-common:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
-org.zalando:logbook-core:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
-org.zalando:logbook-json:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
-org.zalando:logbook-servlet:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
-org.zalando:logbook-spring-boot-autoconfigure:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
-org.zalando:logbook-spring-boot-starter:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
-org.zalando:logbook-spring:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.zalando:logbook-api:3.7.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.zalando:logbook-common:3.7.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.zalando:logbook-core:3.7.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.zalando:logbook-json:3.7.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.zalando:logbook-servlet:3.7.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.zalando:logbook-spring-boot-autoconfigure:3.7.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.zalando:logbook-spring-boot-starter:3.7.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
+org.zalando:logbook-spring:3.7.1=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
 empty=annotationProcessor,developmentOnly,testAndDevelopmentOnly,testAnnotationProcessor
```

### PR DESCRIPTION
**Pull request by msdousti**
Fix the scope of some dependencies.

## Description

Some dependencies must have the scope `test` or `provided`. Due to a recent change, Logbook transitively includes them on compile or runtime path (for Gradle project). This PR resets the dependency scopes back to what they were supposed to be, as in `3.6.0` version of Logbook.

## Motivation and Context

Fixes #1711 

Here's the diff of the Gradle dependencies from `3.6` to `3.8.0-SNAPSHOT` (this PR):

```diff
71,78c71,78
< org.zalando:logbook-api:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
< org.zalando:logbook-common:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
< org.zalando:logbook-core:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
< org.zalando:logbook-json:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
< org.zalando:logbook-servlet:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
< org.zalando:logbook-spring-boot-autoconfigure:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
< org.zalando:logbook-spring-boot-starter:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
< org.zalando:logbook-spring:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
---
> org.zalando:logbook-api:3.8.0-SNAPSHOT=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
> org.zalando:logbook-common:3.8.0-SNAPSHOT=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
> org.zalando:logbook-core:3.8.0-SNAPSHOT=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
> org.zalando:logbook-json:3.8.0-SNAPSHOT=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
> org.zalando:logbook-servlet:3.8.0-SNAPSHOT=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
> org.zalando:logbook-spring-boot-autoconfigure:3.8.0-SNAPSHOT=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
> org.zalando:logbook-spring-boot-starter:3.8.0-SNAPSHOT=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
> org.zalando:logbook-spring:3.8.0-SNAPSHOT=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
```

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by msdousti** [comment]
@bwaldvogel Thanks a lot for detailing the issue. I created this PR to address it.

I also created the dependency diff (see the PR description), and it seems to be OK. It will be great if you can confirm:

1. Build & install Logbook with `mvn install -DskipTests -Ddependency-check.skip=true -Djacoco.skip=true`
2. Add `mavenLocal()` to your Gradle repositories.
3. Add `implementation 'org.zalando:logbook-spring-boot-starter:3.8.0-SNAPSHOT'` to your Gradle dependencies.
4. Check transitive dependencies.

Thanks!

**Comment by bwaldvogel** [comment]
Thanks, it seems to look good!

**Comment by msdousti** [comment]
@bwaldvogel Thanks a lot for confirmation 🙏

@kasmarian I have overlooked some dependencies in my previous PR. The approach here guarantees that the same mistake won't happen.

**Comment by kasmarian** [comment]
👍

**Pull request merged**
