### PR TITLE
wrap ktor client response handling into HttpClient context

### PR DESCRIPTION
**Pull request by kasmarian**
## Description
Wrapping Ktor client response handling in the coroutine context of HttpClient scope. 

## Motivation and Context

Addresses #1822 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by grassehh** [comment]
Thanks for your review :) 
However, are you sure the `Dispatcher.Unconfined` is not an issue too though? Because somehow [this test](https://github.com/grassehh/issues/blob/30a6f58be310473edf2a138b91bcf2a6fd003ded/zalando-logbook-1822/src/test/kotlin/com/grassehh/ClientTest.kt#L45) never responds when I try with your code. And when I just change the `Dispatcher` to `IO` it works again.

Note that in Kotlin [CoroutineDispatcher](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-dispatcher/) documentation they indicate that _"The Unconfined dispatcher should not normally be used in code"_

**Comment by kasmarian** [comment]
Interesting, I tried to replicate this test with `Should log request and response with big body` one. And it was failing before the fix. But I didn't re-run the tests on your repo. Let me check that.

I'm not sure about the IO Dispatcher just because not all clients may want it to be used. I see that if I change the context to the current one (coroutineContext) your test also passes. I wonder why my test didn't capture this? :thinking:

**Comment by grassehh** [comment]
> Interesting, I tried to replicate this test with `Should log request and response with big body` one. And it was failing before the fix. But I didn't re-run the tests on your repo. Let me check that.
> 
> I'm not sure about the IO Dispatcher just because not all clients may want it to be used. I see that if I change the context to the current one (coroutineContext) your test also passes. I wonder why my test didn't capture this? 🤔

Good catch ! Seems like a better solution indeed.

**Comment by ChristianLohmann** [comment]
:+1:

**Pull request merged**
