### PR TITLE
Bump httpclient5 from 5.1.3 to 5.2.1

### PR DESCRIPTION
**Pull request by kumarprabhashanand**
## Description

Bumps [httpclient5](https://github.com/apache/httpcomponents-client) from 5.1.3 to 5.2.1. and Closes https://github.com/zalando/logbook/pull/1444

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by kumarprabhashanand** [comment]
Closes #1444

**Comment by kasmarian** [comment]
👍

**Comment by kasmarian** [comment]
Thank you for the PR!

**Comment by kumarprabhashanand** [comment]
@kasmarian Thanks for approving and merging!

**Pull request merged**
