### PR TITLE
1360-NPE-at-FeignLogbookLogger

### PR DESCRIPTION
**Pull request by hgabor83**
1360-NPE-at-FeignLogbookLogger: if response body is empty then don't throw NPE, tests are fixed.

## Description
#1360 

## Motivation and Context
So if a response from a server comes without body then FeignLogbookLogger throws an NPE, instead of logging the correct response, like in my example 401 Unauthorized. With my fix we avoid NPE in such cases. The empty body related test was wrong I fixed it as well to test this new bugfix.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by hgabor83** [comment]
@whiskeysierra or @lukasniemeier-zalando or @AlexanderYastrebov  could you please approve it? It's just a small modification, but would be very useful to fix this issue.

**Comment by hgabor83** [comment]
Hi, could you please review this PR? We would need this essential fix as soon as possible. Thank you.

**Comment by kasmarian** [comment]
Hi @hgabor83, sorry for the silence. Could you please merge main branch again to have a green build?

**Comment by kasmarian** [comment]
:+1:

**Pull request merged**
