### PR TITLE
Apache http client 5

### PR DESCRIPTION
**Pull request by sokomishalov**
Original issue: https://github.com/zalando/logbook/issues/1008
P.S. Reactive adapter hasn't been implemented yet

### CODE REVIEW

**Comment by whiskeysierra** [comment]
@sokomishalov Looks good, it's just one failing test left.

**Comment by sokomishalov** [comment]
@whiskeysierra I've fixed the test and rebased on main branch

**Comment by whiskeysierra** [comment]
👍

**Comment by whiskeysierra** [comment]
@sokomishalov Thank you for your contribution! 🎉

**Pull request merged**
