### PR TITLE
Fix NullPointerException when the element value is null and PathNotFoundException when body is unwrapped Array

### PR DESCRIPTION
**Pull request by ismail2ov**
We are using JsonPath dynamic value replacement, but when any JSON element has a null value, we get a  NullPointerException. 
This RP fixes this issue.

### CODE REVIEW

**Comment by fatroom** [comment]
👍

**Comment by whiskeysierra** [comment]
Does the NPE come from our use of `toString()` there? Instead of not calling the replacement function, what about allowing the replacement function to handle null itself? That would be a breaking change though.

**Comment by ismail2ov** [comment]
Yes, the NPE came from the use of toString (). I try to handle the exception in the  replacement function, but the NPE came before the execution of the function.

**Comment by whiskeysierra** [comment]
> I try to handle the exception in the replacement function, but the NPE came before the execution of the function.

Yes, correct.

I see two options so far:

1. Detect null, translate to a `NullNode`, don't call the replacement function:
   * Pros:
     * Fixes NPE
   * Cons:  
     * Does't allow replacing of absent or `null` values.
2. Detect null, translate it to `null` (don't call `toString` on it), pass it to the replacement function:
   * Pros:
     * Fixes NPE
     * Does't allow replacing of absent or `null` values.
   * Cons:  
     * Technically breaks existing clients who have non-nullsafe replacement functions.
       **Although, due to this bug right now, they are broken anyway.**

**Comment by ismail2ov** [comment]
What would be the reason for substituting null or absent values?  We use it to obfuscate sensitive data like phone, card number...
Existing customers who have non-null safe replacement features already have a problem.

**Comment by ismail2ov** [comment]
I have also added the PathNotFoundException correction when the body is unwrapped Array. This happens because JsonProvider is defined as com.jayway.jsonpath.spi.json.JacksonJsonNodeJsonProvider

**Comment by ismail2ov** [comment]
@whiskeysierra Can you check this PR?

**Comment by atrujillofalcon** [comment]
@ismail2ov +1

**Pull request closed without merging**
