### PR TITLE
Possible fix for #1071

### PR DESCRIPTION
**Pull request by sokomishalov**
Possible fix for #1071

### CODE REVIEW

**Comment by whiskeysierra** [comment]
Good catch! Looks like a typical copy-&-paste error... 🤦‍♂️

**Comment by whiskeysierra** [comment]
👍

**Comment by whiskeysierra** [comment]
👍

**Comment by sokomishalov** [comment]
> Good catch! Looks like a typical copy-&-paste error... 🤦‍♂️

I supposed the same but was worried a bit if there is some explanation for this line

**Pull request merged**
