### PR TITLE
[fix] Java URI cannot handle netty URIs

### PR DESCRIPTION
**Pull request by bomgar**
## Description
The log files are filled with this:

```
java.lang.IllegalArgumentException: Illegal character in query at index 44: /libs/dam/merge/metadata.json;%0A.json?path=<h1>Rhack&;%0A.inc.js
	at java.base/java.net.URI.create(Unknown Source)
	at org.zalando.logbook.netty.Request.<init>(Request.java:43)
	at org.zalando.logbook.netty.LogbookServerHandler.lambda$channelRead$0(LogbookServerHandler.java:45)
	at org.zalando.fauxpas.ThrowingConsumer.accept(ThrowingConsumer.java:19)
	at org.zalando.logbook.netty.Conditionals.runIf(Conditionals.java:17)
	at org.zalando.logbook.netty.LogbookServerHandler.channelRead(LogbookServerHandler.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:
```

For a lot of malicous URLs this is logged as an error.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by sdousti** [comment]
👍

**Comment by nezygis** [comment]
Any update on this? We're also facing this issue and really appreciate it being merged.

**Comment by sdousti** [comment]
@nezygis We followed a hack to fix this in our projects, as this PR wasn't merged by Logbook team for a long time.

If you like, you can see out hack here:
https://github.bus.zalan.do/Rainbow/buyinghome-gateway/tree/master/src/main/java/org/zalando/logbook/netty

**Comment by nezygis** [comment]
> https://github.bus.zalan.do/Rainbow/buyinghome-gateway/tree/master/src/main/java/org/zalando/logbook/netty

Hello, seems like this is not a public repo, so I cannot see the code.

**Comment by sdousti** [comment]
@nezygis Sorry, please check my updated answer above.

**Comment by nezygis** [comment]
@sdousti thanks a lot, I'll take a look. I'm assuming you also use your own configuration instead of just using "org.zalando:logbook-spring-boot-webflux-autoconfigure" ?

**Comment by sdousti** [comment]
@nezygis My pleasure :)
Also, your assumption is correct: We use that dependency neither directly nor transitively.

**Comment by msdousti** [comment]
👍

**Pull request merged**
