### PR TITLE
Only include zalando loogbook dependencies in logbook-bom

### PR DESCRIPTION
**Pull request by aschugunov**
## Description

root pom.xml contains the only list of modules and common description
logbook-parent contains \<dependencyManagement/>, \<properties/> and etc. from previous root pom
logbook-bom does not have a dependency on the parent module with its own import of dependencies
Version of kotlin-maven-plugin was added

## Motivation and Context

resolves https://github.com/zalando/logbook/issues/1086

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
@aschugunov Thank you for contributing! 📣  Can you rebase onto master to resolve the conflict?

**Comment by whiskeysierra** [comment]
👍

**Comment by whiskeysierra** [comment]
@aschugunov I'm sorry, there is another conflict. I merged PRs in the wrong order...

**Comment by aschugunov** [comment]
> @aschugunov I'm sorry, there is another conflict. I merged PRs in the wrong order...

Don't worry :) 

I found out dependabot updates a little bit ugly 
actually there are two different versions like spring-boot1 and spring-boot2 but dependabot updates only one
So I guess it should be resolved in another issue

**Comment by whiskeysierra** [comment]
👍

**Comment by whiskeysierra** [comment]
@aschugunov Thank you for your contribution, much appreciated! 📣

**Pull request merged**
