### PR TITLE
Add an Intercepter for okhttp v2.x as used by the official kubernetes…

### PR DESCRIPTION
**Pull request by davidwcarlson**
… java client and other projects

## Description
A new logbook intercepter for okhttp v2.x

## Motivation and Context
Many clients are using okhttp, but the only available logbook intercepter is for version 3.x.  This patch provides a solution for those clients on okhttp version 2.x.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ X] My change requires a change to the documentation.
- [ X] I have updated the documentation accordingly.
- [X ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
Thanks for the pull request! Sorry for taking so long, I'm currently on parental leave.

Can you give me some information about the differences of OkHttp 2.x and 3.x? Is there a comparison somewhere or migration docs?

**Comment by whiskeysierra** [comment]
> all code that uses OkHttp's com.squareup.okhttp package should upgrade to the okhttp3 package

Alright, that's a rather drastic change.

> I abandoned in favor of just creating a different implementation.

Reasonable.

**Comment by whiskeysierra** [comment]
Have you tested it with your real-world setup already?

**Comment by davidwcarlson** [comment]
Yes.

**Comment by whiskeysierra** [comment]
All our projects are currently suffering from https://github.com/jeremylong/DependencyCheck/issues/1229#issuecomment-447786312

I'll try to workaround that so I can get this released.

**Comment by whiskeysierra** [comment]
Released as 1.12.0. Thanks a lot for the contribution! :tada:

**Pull request merged**
