### PR TITLE
Added bill of materials

### PR DESCRIPTION
**Pull request by whiskeysierra**
## Description

Logbook has already 5+ modules that produce individual artifacts. Users that depend on them will usually list them all as dependencies in their POMs. Right now we guarantee that version numbers across modules are always the same, i.e. a new release will release each module, even if it wasn't change.
That allows users right now already to use a single maven property `logbook.version` that is used for each dependency. 

This pull requests introduces a BOM (bill of material) as an alternative. The BOM can be imported in the `dependencyManagement` section of a POM. 

## Motivation and Context

The BOM removes the need to specify any version on individual logbook artifacts.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by lukasniemeier-zalando** [comment]
:+1:

**Comment by whiskeysierra** [comment]
Shouldn't the version be inherited from the parent?

**Comment by rainermueller** [comment]
Compared to `org.springframework:spring-framework-bom` and others every dependency defines the version.

**Comment by whiskeysierra** [comment]
Would you mind creating a pull request?

**Comment by rainermueller** [comment]
Done, see [Update bill of materials (BOM) to define version for each dependency](https://github.com/zalando/logbook/pull/379)

**Pull request merged**
