### PR TITLE
Add cookie value replacer function

### LINKED ISSUE #964: Add cookie masking support
Instead of replacing matched values with a constant string, cookie values can be manipulated with a function

Hence, some logs are correlated with a session for debugging purposes, very like in [this issue](https://github.com/zalando/logbook/issues/755).

`HeaderFilters` can provide a `CookieHeaderFilter` with a `Function<String, String>`, also supporting `value -> replace` not to make a breaking change.

### PR DESCRIPTION
**Pull request by nyilmaz**
Instead of replacing with a constant string, cookie values could be configured for masking with a `Function`

## Motivation and Context
Resolves #964

- [x] New feature (non-breaking change which adds functionality)

I can add a tiny doc for this if requested.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
Sorry for the late reaction! 😔

LGTM. Can you rebase to get the build to pass?

**Comment by nyilmaz** [comment]
no problem, @whiskeysierra rebased from main

**Comment by whiskeysierra** [comment]
👍

**Comment by whiskeysierra** [comment]
@nyilmaz Thank you for your contribution! I just released it as 2.6.0 🙏

**Pull request merged**
