### PR TITLE
Work in Progress: Removed Guava dependency

### LINKED ISSUE #59: Remove Guava to make logbook lightweight
Hi

I think it's a shame for logbook to get dep on guava which is very huge library
For what I seen, logbook is using java8 and usage of guava in logbook could be replace by basic lambda

If I propose a PR for guava removing, in is there chance to be accepted ?
Thx
Christophe

### PR DESCRIPTION
**Pull request by whiskeysierra**
Fixes #59

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
@whiskeysierra kuck mal #88

**Comment by whiskeysierra** [comment]
> @whiskeysierra kuck mal #88

I know, but that was way back before I refactored pretty much the whole library. It's easier to do it from scratch now.

**Comment by whiskeysierra** [comment]
> @whiskeysierra kuck mal #88
> I know, but that was way back before I refactored pretty much the whole library. It's easier to do it from scratch now.

Nevermind...

**Comment by whiskeysierra** [comment]
See #88

**Pull request closed without merging**
