### PR TITLE
logbook-ktor modules

### PR DESCRIPTION
**Pull request by sokomishalov**
## Description

Client and server [ktor](https://ktor.io/) modules

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
@sokomishalov 📣 Thank you for your contribution! I'm really looking forward to this!

If you can take another look at this failing test case, we can get this merged and released soon.

**Comment by sokomishalov** [comment]
I've finally fixed those failing tests and made some API cleanup.
My main concern is - should we split this module on client and server side? Each of them requires its own non-tiny dep (ktor-client-core-jvm ~630kb, ktor-server-core ~780kb)

**Comment by whiskeysierra** [comment]
>  My main concern is - should we split this module on client and server side? Each of them requires its own non-tiny dep (ktor-client-core-jvm ~630kb, ktor-server-core ~780kb).

Mmh, good question. Which use case do we anticipate the most, client-only, server-only or both within a single codebase?

**Comment by sokomishalov** [comment]
I would expect a single codebase, but we are able to provide it via two separate modules (`logbook-ktor-client` and `logbook-ktor-server`) and one "starter" module (`logbook-ktor`) with both client and server deps.

**Comment by whiskeysierra** [comment]
> I would expect a single codebase, but we are able to provide it via two separate modules (`logbook-ktor-client` and `logbook-ktor-server`) and one "starter" module (`logbook-ktor`) with both client and server deps.

So we would have four modules?

1. `logbook-ktor-common`, common code base, optionally depends on client + server deps
2. `logbook-ktor-client`, depends on common + client deps
3. `logbook-ktor-server`, depends on common + server deps
4. `logbook-ktor`, depends on client + server

**Comment by sokomishalov** [comment]
> 1. `logbook-ktor-common`, common code base, optionally depends on client + server deps

@whiskeysierra I don't think we need a common module - the only common code for now is `@ExperimentalLogbookKtorApi`.
I suppose to introduce common global annotation for optional kotlin cases - `@ExperimentalLogbookApi` to require temporary opt-in for these features. Maybe it would useful somehow later in other kotlin-first modules (such as okhttp).
How do you think?

**Comment by sokomishalov** [comment]
@whiskeysierra Well, It's almost done, just one weird failing test left yet, while locally it's all just fine - I suppose it's some race condition somewhere

**Comment by whiskeysierra** [comment]
👍

**Comment by whiskeysierra** [comment]
Looks great! 📣 Thanks for your contribution! Much appreciated! 🎉 

I'll try to create a new release later today.

**Comment by sokomishalov** [comment]
@whiskeysierra Please take a look at [a bug-fix and test-fix PR for ktor](https://github.com/zalando/logbook/pull/1116) before release.

**Comment by whiskeysierra** [comment]
I'll create a follow-up, bugfix.

**Pull request merged**
